### ISSUE TITLE
Any chance of getting an update -- date options no longer work w Ubuntu 15.04

### ISSUE THREAD

**Issue by TJMcK** [epinna/Unusedpkg#1]
I cannot get options "-d ?" or "-t yyyy-mm-dd" to work under Ubuntu 15.04.  Would appreciate an update as I can't do this myself...

**Comment by epinna** [comment]
I'll work on this, thanks for the advice.

**Comment by ghost** [comment]
I have fixed it in my fork.

**Comment by epinna** [comment]
Just merged and checked, many thanks for your help @hmikihth :)

**Comment by ghost** [comment]
Welcome :)

2016-04-06 21:20 GMT+01:00 Emilio notifications@github.com:
